---
- hosts: all
  tasks:
    - name: Install epel-release
      yum: name=epel-release state=present

    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest

    - name: start nginx
      service:
          name: nginx
          state: started


